### ISSUE TITLE
Mafeedera by Lydie Kouang

### ISSUE THREAD

**Issue by catarinalouza** [TechLabs-Berlin/project_proposals#15]
### What is your project's name?
Mafeedera - an app that helps business improve their carbon footprint

### What's the problem you are trying to solve?
Businesses increasingly have to comply with the ecological transition wanted by the society at large but still lack efficient feedback tools to address environmental regulations.

### What's your idea for a solution to the given "problem"?
Providing a specilized dashboard that allow business, small or large, to track , monitor and then reduce their carbon footprint.

### Which tracks do you think could be involved?
UX, WD

### How do you imagine User Experience Design could contribute to this project?
UX will help provide a user friendly interface, especially to help communicate well in a rich information setting.

### How do you imagine Web Development could contribute to this project?
WD Frontend to help style the app dashboard
WD Backend for structure and data gathering, data linking.

### What are the most important challenges & bottlenecks of your project?
- Making sure that the data are up-to-date and automatically processed.
- Providing an app that gathers a variety of information yet has an interface that is easy to use.

### What are the most important success factors of your project?
- Having everything work well in real time with all sections linked to each other.
- The interface looking visually appealing and showing key information that help make decision.
 
### Do you have any other remarks?
As I am seeking a full stack certification, I would mainly handle the backend but would also like to be involded in the frontend.

**Comment by valiantone** [comment]
Here are the requirements for this project by track.

**UX:** The task for UX is straightforward, however to build an interface that is relevant, researchers will have to gain proper insight from users who are in this field. Since this is a specialized service meant for specific users, please ensure you will have the available connections in your networks to get feedback from for relevant design. Please suggest alternatives if you have thought of ways to get around this.

**WD:** The need for front-end is pretty evident, but you may not have a need for back-end; since their main task will be to put data in to a database service for the application; however they will have the question of where is the data? This is not a collection task, but an acquisition task. You will in-fact also need DS on this since you want to find datasets for this task not simply collect this data at every step which will be very cumbersome for the user.

**DS:** A team of DS techies could help you decide which metrics to show, how to compute them over data and can integrate directly with the front-end team via an API service for results.

**First step, please answer the questions above and then we can move forward to talking team assignment requirements.**

**Comment by nuclyd** [comment]
Thank you for your feedback! Here are my answers to above questions/requirements:

**UX**: I plan on contacting 2 or 3 small business (I have already one in mind) that would give feedback on the tool.

**WD:** The tool is not meant as a general information displayer but rather as a feedback tool that displays carbon accounting based on specific purchase a company has made within a given timeframe. The purchase's data are therefore fed by the user in order to display an output. Some criteria would include distance, material used, origin and we would program the metrics and data translation to it. Measurement standards for it like CO2 Emission can be found online. There is no data acquisition necessary for it meaning no big dataset to acquire and compute complex metric or other algorithms over. It is mostly converting data fed by the company/small business into something that is relevant to carbon monitoring. In this sense, converting and connecting the data to the tool can be done by backend. 

**DS:** The categories displayed will be pretty straightforward: e.g. carbon amount, other environment impact, the variation of the impact and their provenance from different activities of the company. There is therefore no prediction involved nor complex learning from the small data involved.

Attached is a rough map visualization of the tool idea. I hope it provides clarification.

<img width="1015" alt="Capture d’écran 2024-01-16 à 19 21 13" src="https://github.com/TechLabs-Berlin/project_proposals/assets/150607218/4fd1a0b9-0e86-428c-b6e2-8f17735762cf">

**Comment by valiantone** [comment]
Well reasoned @nuclyd (and thank you for the image, it helped). With your response I can say I am convinced that with 2UX and 2WD, we should be able to form a complete team to tackle the project.

Just for the sake of making this a more challenging project and to perhaps make team formation lot easier; I would selfishly push you to consider expanding the scope of the project and perhaps try to recruit some DS techies. Maybe they can help contribute to making this project bigger and better with some DS additions. Try and see if anyone is interested. Final call is yours.

Let's move this project to accepted as well, go forth and find your team.

### Team Formation Requirements
- [ ] 2UX
- [ ] 1 WD (BE)
- [ ] 1 WD (FE)
